CREATE TABLE TAB_EMPRESA(	
    COD_EMPRESA INT IDENTITY(1,1) PRIMARY KEY, -- CHAVE
    NOME		VARCHAR(100),
	CNPJ_CPF	VARCHAR(20)	
)


-----------------------------

CREATE TABLE TAB_USUARIO(	
	COD_EMPRESA	INT NOT NULL, -- CHAVE
    COD_USUARIO INT NOT NULL, -- CHAVE
    NOME		VARCHAR(100),
	EMAIL		VARCHAR(100),
	SENHA		VARCHAR(50),
	TOKEN_ID	VARCHAR(200),
	PLATAFORMA	VARCHAR(10) 
)

ALTER TABLE TAB_USUARIO ADD PRIMARY KEY (COD_EMPRESA, COD_USUARIO)

-----------------------------


CREATE TABLE TAB_NOTIFICACAO(	
    COD_NOTIFICACAO INT IDENTITY(1,1) PRIMARY KEY,  -- CHAVE
	COD_EMPRESA	INT,
	COD_USUARIO INT,
	DATA_NOTIFICACAO DATETIME,
	TITULO		VARCHAR(100),
    TEXTO		VARCHAR(500),	
	IND_LIDO	CHAR(1),
	IND_DESTAQUE CHAR(1)
)


-----------------------------


CREATE TABLE TAB_PRODUTO(
	COD_EMPRESA	INT NOT NULL, -- CHAVE
	COD_PRODUTO	INT NOT NULL, -- CHAVE
	DESCRICAO	VARCHAR(200),
	VALOR		DECIMAL(12,2),
	FOTO		VARCHAR(MAX)
)

ALTER TABLE TAB_PRODUTO ADD PRIMARY KEY (COD_EMPRESA, COD_PRODUTO)

-----------------------------

CREATE TABLE TAB_CLIENTE(
	COD_EMPRESA	INT NOT NULL, -- CHAVE
	COD_CLIENTE	INT NOT NULL, -- CHAVE
	CNPJ_CPF	VARCHAR(20),
	NOME		VARCHAR(100),
	FONE		VARCHAR(20),
	EMAIL		VARCHAR(100),
	ENDERECO	VARCHAR(500),
	OBS			VARCHAR(1000),
	DATA_ULT_COMPRA DATETIME,
	VALOR_ULT_COMPRA DECIMAL(12,2)
)

ALTER TABLE TAB_CLIENTE ADD PRIMARY KEY (COD_EMPRESA, COD_CLIENTE)

-----------------------------

CREATE TABLE TAB_PEDIDO(
	COD_EMPRESA	INT NOT NULL, -- CHAVE
	NUM_PEDIDO	INT NOT NULL, -- CHAVE
	COD_CLIENTE	INT,
	TIPO_PEDIDO	CHAR(1),
	DATA_PEDIDO	DATETIME,
	CONTATO		VARCHAR(100),	
	OBS			VARCHAR(500),
	IND_ENTREGUE CHAR(1),	
	VALOR_TOTAL DECIMAL(12,2),
	COD_USUARIO	INT
)

ALTER TABLE TAB_PEDIDO ADD PRIMARY KEY (COD_EMPRESA, NUM_PEDIDO)

-----------------------------

CREATE TABLE TAB_PEDIDO_ITEM(
	COD_EMPRESA	INT NOT NULL, -- CHAVE
	NUM_PEDIDO	INT NOT NULL, -- CHAVE
	SEQ_ITEM	INT NOT NULL, -- CHAVE
	COD_PRODUTO	INT,
	QTD			INT,	
	VALOR_UNIT	DECIMAL(12,2),
	VALOR_TOTAL DECIMAL(12,2)
)

ALTER TABLE TAB_PEDIDO_ITEM ADD PRIMARY KEY (COD_EMPRESA, NUM_PEDIDO, SEQ_ITEM)
